import "./globals.css";
import Header from "@/shared/header/header";
import Footer from "@/shared/footer/footer";
import { Toaster } from "react-hot-toast";
import { auth } from "@/auth";
import { UserContextProvider } from "@/context/userContextProvider";
import { prisma } from "@/utils/prisma";
import { Nunito_Sans } from "next/font/google";

const nunito = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
})

export const metadata = {
  title: "Gawalaty",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  let userImage = null;
  let userWishlist = null;
  if (session?.user) {
    userImage = session?.user?.image
    userWishlist = await prisma.wishlist.findMany({ where: { userid: session.user.id }, select: { tripid: true } })
    if(userWishlist?.length>0){userWishlist = userWishlist.map(w=>w.tripid)}
  }
  return (
    <html lang="en">
      <body
        className={` ${nunito.variable}  antialiased`}
      >
        <UserContextProvider userImage={userImage} userWishlist={userWishlist}>
          <>
            <Header />
            <Toaster />
            {children}
            <Footer />
          </>
        </UserContextProvider>
      </body>
    </html>
  );
}
